channels:
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-defaults
      - azure-ml-api-sdk
      - nibabel
      - scikit-learn
      - scipy
      - pandas
      - openvino-dev
      - torch==1.13.1+cpu
      - torchvision==0.14.1+cpu
      - intel_extension_for_pytorch==1.13.100
      - torchio
      - "--index-url https://pypi.org/simple/"
      - "--extra-index-url https://download.pytorch.org/whl/cpu"
